# Generated by Django 5.2 on 2025-05-27 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ('id',), 'verbose_name': 'Cart', 'verbose_name_plural': 'Carts'},
        ),
    ]
