# Generated by Django 5.2 on 2025-05-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, error_messages={'unique': 'This email is already in use.'}, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
