# Generated by Django 5.2 on 2025-05-27 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_categories_options_products_is_new_and_more'),
        ('reviews', '0002_rename_reviewmodel_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='goods.products', verbose_name='Product'),
        ),
    ]
